export default {
  todaysMedication: [
    {
      time: "8:00 PM",
      frequency: "Daily",
      name: "Xanax",
      amountInGrams: 1,
      quantityLeftInDays: 120,
      fillsLeft: 14,
      image: require("./assets/pill.png"),
    },
    {
      time: "8:00 PM",
      frequency: "Daily",
      name: "Xanax",
      amountInGrams: 1,
      quantityLeftInDays: 120,
      fillsLeft: 14,
      image: require("./assets/pill.png"),
    },
    {
      time: "8:00 PM",
      frequency: "Daily",
      name: "Xanax",
      amountInGrams: 1,
      quantityLeftInDays: 120,
      fillsLeft: 14,
      image: require("./assets/pill.png"),
    },
    {
      time: "8:00 PM",
      frequency: "Daily",
      name: "Xanax",
      amountInGrams: 1,
      quantityLeftInDays: 120,
      fillsLeft: 14,
      image: require("./assets/pill.png"),
    },
    {
      time: "8:00 PM",
      frequency: "Daily",
      name: "Xanax",
      amountInGrams: 1,
      quantityLeftInDays: 120,
      fillsLeft: 14,
      image: require("./assets/pill.png"),
    },
    {
      time: "8:00 PM",
      frequency: "Daily",
      name: "Xanax",
      amountInGrams: 1,
      quantityLeftInDays: 120,
      fillsLeft: 14,
      image: require("./assets/pill.png"),
    },
  ],
  appointments: [
    {
      name: "Dr. Godlstein",
      month: "APR",
      day: "16",
      time: "12:00 PM",
      image: require("./assets/person.jpeg"),
    },
    {
      name: "Dr. Godlstein",
      month: "APR",
      day: "16",
      time: "12:00 PM",
      image: require("./assets/person.jpeg"),
    },
    {
      name: "Dr. Godlstein",
      month: "APR",
      day: "16",
      time: "12:00 PM",
      image: require("./assets/person.jpeg"),
    },
    {
      name: "Dr. Godlstein",
      month: "APR",
      day: "16",
      time: "12:00 PM",
      image: require("./assets/person.jpeg"),
    },
    {
      name: "Dr. Godlstein",
      month: "APR",
      day: "16",
      time: "12:00 PM",
      image: require("./assets/person.jpeg"),
    },
    {
      name: "Dr. Godlstein",
      month: "APR",
      day: "16",
      time: "12:00 PM",
      image: require("./assets/person.jpeg"),
    },
  ],
  medication: [
    {
      frequency: "1 pill daily every morning",
      name: "Xanax",
      amountInGrams: 1,
      quantityLeftInDays: 120,
      fillsLeft: 14,
      rx: 32543782,
      directions: "Take with food everyday",
      prescribedBy: "Dr. Goldstein",
      image: require("./assets/pill.png"),
    },
    {
      frequency: "1 pill daily every morning",
      name: "Xanax",
      amountInGrams: 1,
      quantityLeftInDays: 120,
      fillsLeft: 14,
      rx: 32543782,
      directions: "Take with food everyday",
      prescribedBy: "Dr. Goldstein",
      image: require("./assets/pill.png"),
    },
    {
      frequency: "1 pill daily every morning",
      name: "Xanax",
      amountInGrams: 1,
      quantityLeftInDays: 120,
      fillsLeft: 14,
      rx: 32543782,
      directions: "Take with food everyday",
      prescribedBy: "Dr. Goldstein",
      image: require("./assets/pill.png"),
    },
    {
      frequency: "1 pill daily every morning",
      name: "Xanax",
      amountInGrams: 1,
      quantityLeftInDays: 120,
      fillsLeft: 14,
      rx: 32543782,
      directions: "Take with food everyday",
      prescribedBy: "Dr. Goldstein",
      image: require("./assets/pill.png"),
    },
    {
      frequency: "1 pill daily every morning",
      name: "Xanax",
      amountInGrams: 1,
      quantityLeftInDays: 120,
      fillsLeft: 14,
      rx: 32543782,
      directions: "Take with food everyday",
      prescribedBy: "Dr. Goldstein",
      image: require("./assets/pill.png"),
    },
  ],
};
